ALTER TABLE ai_tasks ADD COLUMN IF NOT EXISTS total_tokens INTEGER DEFAULT 0;
ALTER TABLE ai_tasks ADD COLUMN IF NOT EXISTS total_cost DECIMAL(10,4) DEFAULT 0;
ALTER TABLE ai_answers ADD COLUMN IF NOT EXISTS tokens_used INTEGER DEFAULT 0;
ALTER TABLE ai_answers ADD COLUMN IF NOT EXISTS cost DECIMAL(10,4) DEFAULT 0;
